name: yh_lwgl
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.1.9
  # 网络库 https://github.com/flutterchina/dio
  dio: ^1.0.9
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.21.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.0
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.0.2
  #状态管理
  redux: "^3.0.0"
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.0.0
  # listView 加载等待loading https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^3.1.0
  #事件
  event_bus: ^1.0.1

  #适量动画 https://github.com/CarSmallGuo/Flare-Flutter
  flare_flutter:
    git:
      url: https://github.com/CarSmallGuo/Flare-Flutter.git
      path: flare_flutter
      ref: c7a59c9cff8887abb89f2c36b3911f5fbdf189c8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/img_login_bg.png
     - assets/images/img_logo.png
     - assets/images/img_app_name.png

     - assets/images/img_syn_check.png
     - assets/images/img_text_manage_file.png
     - assets/images/img_text_manage_knowledge.png
     - assets/images/img_text_manage_law.png
     - assets/images/img_text_manage_plan.png
     - assets/images/img_icon_notice.png
     - assets/images/img_icon_notice_none.png
     - assets/images/img_icon_contact.png
     - assets/images/img_icon_contact_none.png
     - assets/images/img_icon_home.png
     - assets/images/img_icon_home_none.png
     - assets/images/img_icon_mine.png
     - assets/images/img_icon_mine_none.png
     - assets/images/img_text_manager.png
     - assets/images/img_person_manager.png
     - assets/images/img_special_check.png
     - assets/images/img_danger_fast_repost.png
     - assets/images/img_danger_manage.png
     - assets/images/img_text_manage_system.png
     - assets/images/img_text_manage_search.png
     - assets/images/ic_save_file.png
     - assets/images/ic_error.png
     - assets/images/ic_arrow_right.png
     - assets/images/img_icon_publish.png
     - assets/images/img_icon_over.png
     - assets/images/img_icon_outed.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
