
class FxyhListData {
	dynamic modifiedTime;
	dynamic endDate;
	dynamic organNo;
	dynamic wyhDescription;
	int zybwId;
	dynamic zgyzDescription;
	String checkedTime;
	dynamic operType;
	int yhxxStatus;
	dynamic xjjhxqId;
	dynamic currentUserId;
	int yhxxLevel;
	String createdTime;
	int verifyPerson;
	dynamic fileList;
	dynamic images;
	int createdStaffId;
	String reformPersonName;
	int yhxxId;
	dynamic xjjhId;
	String verifyPersonName;
	dynamic fjwjBms;
	dynamic undealYhxxCount;
	dynamic itemJcbz;
	dynamic fjwjFwdzs;
	dynamic operationTime;
	String yhxxDescription;
	int yhqdFxdj;
	int organId;
	dynamic operationType;
	int yhxxSource;
	dynamic projectName;
	String checkedPersonName;
	dynamic startDate;
	dynamic modifiedStaffName;
	dynamic newReformDeadline;
	dynamic statusStr;
	dynamic yhxxHistoryId;
	String checkedContent;
	dynamic operationPerson;
	dynamic fjwjBmid;
	dynamic yhtbId;
	String yhxxStatusName;
	dynamic verifyStatus;
	String yhxxPosition;
	dynamic hasYhxxFlag;
	dynamic realPath;
	dynamic operationPersonName;
	dynamic enterpriseName;
	dynamic fjwjYwjms;
	dynamic modifiedStaffId;
	String filePath;
	dynamic yhxxCount;
	dynamic keyName;
	dynamic fjwjWjms;
	int xjjhxqSource;
	int yhqdItemId;
	dynamic checkedDescription;
	String createdStaffName;
	String organName;
	String reformDeadline;
	dynamic deletedFlag;
	int reformPerson;
	dynamic yhxxSourceStr;
	dynamic fjwjIds;
	dynamic xjjhName;
	int checkedPerson;
	String reformDemand;
	dynamic staffId;

	FxyhListData({this.modifiedTime, this.endDate, this.organNo, this.wyhDescription, this.zybwId, this.zgyzDescription, this.checkedTime, this.operType, this.yhxxStatus, this.xjjhxqId, this.currentUserId, this.yhxxLevel, this.createdTime, this.verifyPerson, this.fileList, this.images, this.createdStaffId, this.reformPersonName, this.yhxxId, this.xjjhId, this.verifyPersonName, this.fjwjBms, this.undealYhxxCount, this.itemJcbz, this.fjwjFwdzs, this.operationTime, this.yhxxDescription, this.yhqdFxdj, this.organId, this.operationType, this.yhxxSource, this.projectName, this.checkedPersonName, this.startDate, this.modifiedStaffName, this.newReformDeadline, this.statusStr, this.yhxxHistoryId, this.checkedContent, this.operationPerson, this.fjwjBmid, this.yhtbId, this.yhxxStatusName, this.verifyStatus, this.yhxxPosition, this.hasYhxxFlag, this.realPath, this.operationPersonName, this.enterpriseName, this.fjwjYwjms, this.modifiedStaffId, this.filePath, this.yhxxCount, this.keyName, this.fjwjWjms, this.xjjhxqSource, this.yhqdItemId, this.checkedDescription, this.createdStaffName, this.organName, this.reformDeadline, this.deletedFlag, this.reformPerson, this.yhxxSourceStr, this.fjwjIds, this.xjjhName, this.checkedPerson, this.reformDemand, this.staffId});

	FxyhListData.fromJson(Map<String, dynamic> json) {
		modifiedTime = json['modifiedTime'];
		endDate = json['endDate'];
		organNo = json['organNo'];
		wyhDescription = json['wyhDescription'];
		zybwId = json['zybwId'];
		zgyzDescription = json['zgyzDescription'];
		checkedTime = json['checkedTime'];
		operType = json['operType'];
		yhxxStatus = json['yhxxStatus'];
		xjjhxqId = json['xjjhxqId'];
		currentUserId = json['currentUserId'];
		yhxxLevel = json['yhxxLevel'];
		createdTime = json['createdTime'];
		verifyPerson = json['verifyPerson'];
		fileList = json['fileList'];
		images = json['images'];
		createdStaffId = json['createdStaffId'];
		reformPersonName = json['reformPersonName'];
		yhxxId = json['yhxxId'];
		xjjhId = json['xjjhId'];
		verifyPersonName = json['verifyPersonName'];
		fjwjBms = json['fjwjBms'];
		undealYhxxCount = json['undealYhxxCount'];
		itemJcbz = json['itemJcbz'];
		fjwjFwdzs = json['fjwjFwdzs'];
		operationTime = json['operationTime'];
		yhxxDescription = json['yhxxDescription'];
		yhqdFxdj = json['yhqdFxdj'];
		organId = json['organId'];
		operationType = json['operationType'];
		yhxxSource = json['yhxxSource'];
		projectName = json['projectName'];
		checkedPersonName = json['checkedPersonName'];
		startDate = json['startDate'];
		modifiedStaffName = json['modifiedStaffName'];
		newReformDeadline = json['newReformDeadline'];
		statusStr = json['statusStr'];
		yhxxHistoryId = json['yhxxHistoryId'];
		checkedContent = json['checkedContent'];
		operationPerson = json['operationPerson'];
		fjwjBmid = json['fjwjBmid'];
		yhtbId = json['yhtbId'];
		yhxxStatusName = json['yhxxStatusName'];
		verifyStatus = json['verifyStatus'];
		yhxxPosition = json['yhxxPosition'];
		hasYhxxFlag = json['hasYhxxFlag'];
		realPath = json['realPath'];
		operationPersonName = json['operationPersonName'];
		enterpriseName = json['enterpriseName'];
		fjwjYwjms = json['fjwjYwjms'];
		modifiedStaffId = json['modifiedStaffId'];
		filePath = json['filePath'];
		yhxxCount = json['yhxxCount'];
		keyName = json['keyName'];
		fjwjWjms = json['fjwjWjms'];
		xjjhxqSource = json['xjjhxqSource'];
		yhqdItemId = json['yhqdItemId'];
		checkedDescription = json['checkedDescription'];
		createdStaffName = json['createdStaffName'];
		organName = json['organName'];
		reformDeadline = json['reformDeadline'];
		deletedFlag = json['deletedFlag'];
		reformPerson = json['reformPerson'];
		yhxxSourceStr = json['yhxxSourceStr'];
		fjwjIds = json['fjwjIds'];
		xjjhName = json['xjjhName'];
		checkedPerson = json['checkedPerson'];
		reformDemand = json['reformDemand'];
		staffId = json['staffId'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['modifiedTime'] = this.modifiedTime;
		data['endDate'] = this.endDate;
		data['organNo'] = this.organNo;
		data['wyhDescription'] = this.wyhDescription;
		data['zybwId'] = this.zybwId;
		data['zgyzDescription'] = this.zgyzDescription;
		data['checkedTime'] = this.checkedTime;
		data['operType'] = this.operType;
		data['yhxxStatus'] = this.yhxxStatus;
		data['xjjhxqId'] = this.xjjhxqId;
		data['currentUserId'] = this.currentUserId;
		data['yhxxLevel'] = this.yhxxLevel;
		data['createdTime'] = this.createdTime;
		data['verifyPerson'] = this.verifyPerson;
		data['fileList'] = this.fileList;
		data['images'] = this.images;
		data['createdStaffId'] = this.createdStaffId;
		data['reformPersonName'] = this.reformPersonName;
		data['yhxxId'] = this.yhxxId;
		data['xjjhId'] = this.xjjhId;
		data['verifyPersonName'] = this.verifyPersonName;
		data['fjwjBms'] = this.fjwjBms;
		data['undealYhxxCount'] = this.undealYhxxCount;
		data['itemJcbz'] = this.itemJcbz;
		data['fjwjFwdzs'] = this.fjwjFwdzs;
		data['operationTime'] = this.operationTime;
		data['yhxxDescription'] = this.yhxxDescription;
		data['yhqdFxdj'] = this.yhqdFxdj;
		data['organId'] = this.organId;
		data['operationType'] = this.operationType;
		data['yhxxSource'] = this.yhxxSource;
		data['projectName'] = this.projectName;
		data['checkedPersonName'] = this.checkedPersonName;
		data['startDate'] = this.startDate;
		data['modifiedStaffName'] = this.modifiedStaffName;
		data['newReformDeadline'] = this.newReformDeadline;
		data['statusStr'] = this.statusStr;
		data['yhxxHistoryId'] = this.yhxxHistoryId;
		data['checkedContent'] = this.checkedContent;
		data['operationPerson'] = this.operationPerson;
		data['fjwjBmid'] = this.fjwjBmid;
		data['yhtbId'] = this.yhtbId;
		data['yhxxStatusName'] = this.yhxxStatusName;
		data['verifyStatus'] = this.verifyStatus;
		data['yhxxPosition'] = this.yhxxPosition;
		data['hasYhxxFlag'] = this.hasYhxxFlag;
		data['realPath'] = this.realPath;
		data['operationPersonName'] = this.operationPersonName;
		data['enterpriseName'] = this.enterpriseName;
		data['fjwjYwjms'] = this.fjwjYwjms;
		data['modifiedStaffId'] = this.modifiedStaffId;
		data['filePath'] = this.filePath;
		data['yhxxCount'] = this.yhxxCount;
		data['keyName'] = this.keyName;
		data['fjwjWjms'] = this.fjwjWjms;
		data['xjjhxqSource'] = this.xjjhxqSource;
		data['yhqdItemId'] = this.yhqdItemId;
		data['checkedDescription'] = this.checkedDescription;
		data['createdStaffName'] = this.createdStaffName;
		data['organName'] = this.organName;
		data['reformDeadline'] = this.reformDeadline;
		data['deletedFlag'] = this.deletedFlag;
		data['reformPerson'] = this.reformPerson;
		data['yhxxSourceStr'] = this.yhxxSourceStr;
		data['fjwjIds'] = this.fjwjIds;
		data['xjjhName'] = this.xjjhName;
		data['checkedPerson'] = this.checkedPerson;
		data['reformDemand'] = this.reformDemand;
		data['staffId'] = this.staffId;
		return data;
	}
}
