

class TzzyryData {
	String tzzyNl;
	dynamic zwId;
	dynamic modifiedTime;
	dynamic tzzyFzrq;
	dynamic createdStaffid;
	dynamic sfzUpfiles;
	dynamic endDate;
	dynamic modifiedStaffid;
	String txFjwjFwdz;
	dynamic zwName;
	String tzzyGzbz;
	dynamic tzzyFsrq;
	dynamic tableName;
	int zsCount;
	dynamic zsList;
	dynamic tzzyTcrq;
	dynamic sfzList;
	int txCount;
	String createdTime;
	dynamic tzzyBz;
	dynamic zsUpfiles;
	String tzzyJcrq;
	int tzzyId;
	dynamic tzzyGzdd;
	int tzzyRyzt;
	String tzzySfzh;
	dynamic keyName;
	dynamic tzzyRyztQuery;
	dynamic tzzyTcrqAfter;
	dynamic tzzyJszc;
	String tzzyXb;
	dynamic txFjwjYwjm;
	dynamic organName;
	String tzzyAqzs;
	int deletedFlag;
	dynamic txUpfiles;
	String tzzyXm;
	int organId;
	String tzzyGz;
	dynamic tzzyRygzQuery;
	dynamic tzzyFzbm;
	int sfzCount;
	dynamic startDate;

	TzzyryData({this.tzzyNl, this.zwId, this.modifiedTime, this.tzzyFzrq, this.createdStaffid, this.sfzUpfiles, this.endDate, this.modifiedStaffid, this.txFjwjFwdz, this.zwName, this.tzzyGzbz, this.tzzyFsrq, this.tableName, this.zsCount, this.zsList, this.tzzyTcrq, this.sfzList, this.txCount, this.createdTime, this.tzzyBz, this.zsUpfiles, this.tzzyJcrq, this.tzzyId, this.tzzyGzdd, this.tzzyRyzt, this.tzzySfzh, this.keyName, this.tzzyRyztQuery, this.tzzyTcrqAfter, this.tzzyJszc, this.tzzyXb, this.txFjwjYwjm, this.organName, this.tzzyAqzs, this.deletedFlag, this.txUpfiles, this.tzzyXm, this.organId, this.tzzyGz, this.tzzyRygzQuery, this.tzzyFzbm, this.sfzCount, this.startDate});

	TzzyryData.fromJson(Map<String, dynamic> json) {
		tzzyNl = json['tzzyNl'];
		zwId = json['zwId'];
		modifiedTime = json['modifiedTime'];
		tzzyFzrq = json['tzzyFzrq'];
		createdStaffid = json['createdStaffid'];
		sfzUpfiles = json['sfzUpfiles'];
		endDate = json['endDate'];
		modifiedStaffid = json['modifiedStaffid'];
		txFjwjFwdz = json['txFjwjFwdz'];
		zwName = json['zwName'];
		tzzyGzbz = json['tzzyGzbz'];
		tzzyFsrq = json['tzzyFsrq'];
		tableName = json['tableName'];
		zsCount = json['zsCount'];
		zsList = json['zsList'];
		tzzyTcrq = json['tzzyTcrq'];
		sfzList = json['sfzList'];
		txCount = json['txCount'];
		createdTime = json['createdTime'];
		tzzyBz = json['tzzyBz'];
		zsUpfiles = json['zsUpfiles'];
		tzzyJcrq = json['tzzyJcrq'];
		tzzyId = json['tzzyId'];
		tzzyGzdd = json['tzzyGzdd'];
		tzzyRyzt = json['tzzyRyzt'];
		tzzySfzh = json['tzzySfzh'];
		keyName = json['keyName'];
		tzzyRyztQuery = json['tzzyRyztQuery'];
		tzzyTcrqAfter = json['tzzyTcrqAfter'];
		tzzyJszc = json['tzzyJszc'];
		tzzyXb = json['tzzyXb'];
		txFjwjYwjm = json['txFjwjYwjm'];
		organName = json['organName'];
		tzzyAqzs = json['tzzyAqzs'];
		deletedFlag = json['deletedFlag'];
		txUpfiles = json['txUpfiles'];
		tzzyXm = json['tzzyXm'];
		organId = json['organId'];
		tzzyGz = json['tzzyGz'];
		tzzyRygzQuery = json['tzzyRygzQuery'];
		tzzyFzbm = json['tzzyFzbm'];
		sfzCount = json['sfzCount'];
		startDate = json['startDate'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['tzzyNl'] = this.tzzyNl;
		data['zwId'] = this.zwId;
		data['modifiedTime'] = this.modifiedTime;
		data['tzzyFzrq'] = this.tzzyFzrq;
		data['createdStaffid'] = this.createdStaffid;
		data['sfzUpfiles'] = this.sfzUpfiles;
		data['endDate'] = this.endDate;
		data['modifiedStaffid'] = this.modifiedStaffid;
		data['txFjwjFwdz'] = this.txFjwjFwdz;
		data['zwName'] = this.zwName;
		data['tzzyGzbz'] = this.tzzyGzbz;
		data['tzzyFsrq'] = this.tzzyFsrq;
		data['tableName'] = this.tableName;
		data['zsCount'] = this.zsCount;
		data['zsList'] = this.zsList;
		data['tzzyTcrq'] = this.tzzyTcrq;
		data['sfzList'] = this.sfzList;
		data['txCount'] = this.txCount;
		data['createdTime'] = this.createdTime;
		data['tzzyBz'] = this.tzzyBz;
		data['zsUpfiles'] = this.zsUpfiles;
		data['tzzyJcrq'] = this.tzzyJcrq;
		data['tzzyId'] = this.tzzyId;
		data['tzzyGzdd'] = this.tzzyGzdd;
		data['tzzyRyzt'] = this.tzzyRyzt;
		data['tzzySfzh'] = this.tzzySfzh;
		data['keyName'] = this.keyName;
		data['tzzyRyztQuery'] = this.tzzyRyztQuery;
		data['tzzyTcrqAfter'] = this.tzzyTcrqAfter;
		data['tzzyJszc'] = this.tzzyJszc;
		data['tzzyXb'] = this.tzzyXb;
		data['txFjwjYwjm'] = this.txFjwjYwjm;
		data['organName'] = this.organName;
		data['tzzyAqzs'] = this.tzzyAqzs;
		data['deletedFlag'] = this.deletedFlag;
		data['txUpfiles'] = this.txUpfiles;
		data['tzzyXm'] = this.tzzyXm;
		data['organId'] = this.organId;
		data['tzzyGz'] = this.tzzyGz;
		data['tzzyRygzQuery'] = this.tzzyRygzQuery;
		data['tzzyFzbm'] = this.tzzyFzbm;
		data['sfzCount'] = this.sfzCount;
		data['startDate'] = this.startDate;
		return data;
	}
}
